#!/bin/bash
gcc -std=c99 otp_enc_d.c -o otp_enc_d -D_XOPEN_SOURCE
gcc -std=c99 otp_enc.c -o otp_enc
gcc -std=c99 otp_dec_d.c -o otp_dec_d
gcc -std=c99 otp_dec.c -o otp_dec
gcc -std=c99 keygen.c -o keygen
